name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3

      - name: Ruff format check
        run: ruff format --check --diff
        continue-on-error: true

      # Optional: auto-format all files (uncomment if you want to apply fixes automatically)
      # - name: Auto-format with Ruff
      #   run: ruff format .
