name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff requests beautifulsoup4 rich fake_useragent

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3

      - name: Ruff format check
        run: ruff format --check --diff
